In [132]:
import numpy as np

marks = np.array([10,25,36,56,89])

print(marks)
print(marks.shape)
print(marks.ndim)
print(marks.dtype)

[10 25 36 56 89]
(5,)
1
int64


In [133]:
import numpy as np

data = np.array([[10,20,30],
                [40,50,60]
                ])
print(data)
print(data.shape)
print(data.ndim)
print(data.dtype)

[[10 20 30]
 [40 50 60]]
(2, 3)
2
int64


In [134]:
import numpy as np
scores = np.array([55, 72, 81, 93, 68, 47, 89])

print(scores.ndim)
print(scores.shape)
print(scores.size)
print(scores.dtype)

new_score = scores + 5
print(new_score)

1
(7,)
7
int64
[60 77 86 98 73 52 94]


In [135]:
import numpy as np

marks = np.array ([[10 ,20, 30, 40],
         [50 ,60 ,70, 80],
         [90 ,100, 110, 120]
         ])

print(marks.ndim)
print(marks.shape)
print(marks.size)

2
(3, 4)
12


In [136]:
import numpy as np

marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 81, 95],
    [55, 60, 72]
])
print(marks[2,2])
print(marks[2])
print(marks[:,1])
print(marks[0:2,1:3])
print(marks[3])
print(marks[:,2])
print(marks[:2,:2])
print(marks[:,:2])

95
[92 81 95]
[75 88 81 60]
[[75 90]
 [88 70]]
[55 60 72]
[90 70 95 72]
[[80 75]
 [65 88]]
[[80 75]
 [65 88]
 [92 81]
 [55 60]]


In [137]:
import numpy as np

scores = np.array([55, 72, 81, 93, 68, 47, 89])

print(scores[scores > 80])
print(scores[scores < 60])
print(scores[scores >= 70 ])
print(scores[(scores > 70) & (scores < 90)])
print(scores[(scores < 60) | (scores > 90)])
print(scores[~(scores > 70)])


[81 93 89]
[55 47]
[72 81 93 89]
[72 81 89]
[55 93 47]
[55 68 47]


In [138]:
import numpy as np

marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 81, 95],
    [55, 60, 72]
])

print(marks[marks > 80])

[90 88 92 81 95]


In [139]:
import numpy as np

scores = np.array([55, 72, 81, 93, 68, 47, 89])

print(scores[[0,3,6]])
print(scores[[1,4,5]])
print(scores[[6,2,0]])



[55 93 89]
[72 68 47]
[89 81 55]


In [140]:
import numpy as np

marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 81, 95],
    [55, 60, 72]
])
print(marks[[0,2]])
print(marks[[3,1]])
print(marks[:,[0,2]])

[[80 75 90]
 [92 81 95]]
[[55 60 72]
 [65 88 70]]
[[80 90]
 [65 70]
 [92 95]
 [55 72]]


In [141]:
import numpy as np

scores = np.array([55, 72, 81, 93, 68, 47, 89])

print(np.where(scores > 80))
print(np.where(scores >= 80, "Pass","Fail"))

(array([2, 3, 6]),)
['Fail' 'Fail' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass']


In [142]:
import numpy as np

prices = np.array([100, 250, 80, 500, 120])
np.where(prices > 200,prices * 0.8, prices)

array([100., 200.,  80., 400., 120.])

In [143]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 81, 95],
    [55, 60, 72]
])
print(np.where(marks > 80))

(array([0, 1, 2, 2, 2]), array([2, 1, 0, 1, 2]))


In [144]:
age = np.array([16, 21, 35, 17, 42])
print(np.where(age >= 18,"adult","minor"))

['minor' 'adult' 'adult' 'minor' 'adult']


In [145]:
import numpy as np

scores = np.array([55, 72, 81, 93, 68, 47, 89])

print(np.where(scores > 80))
print(np.where(scores < 60))
print(np.where(scores >= 70, "1","0"))
print(np.where(scores>=70,"Pass","Fail"))

(array([2, 3, 6]),)
(array([0, 5]),)
['0' '1' '1' '1' '0' '0' '1']
['Fail' 'Pass' 'Pass' 'Pass' 'Fail' 'Fail' 'Pass']


In [146]:
marks = np.array([
    [80, 75, 90],
    [65, 88, 70],
    [92, 81, 95],
    [55, 60, 72]
])
print(np.where(marks > 90))
print(marks[0,2])

(array([2, 2]), array([0, 2]))
90


In [147]:
np.zeros((100, 25))

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], shape=(100, 25))

In [148]:
arr = np.zeros(7)
print(np.zeros(7))
print(arr.size)
print(arr.shape)
print(arr.ndim)


[0. 0. 0. 0. 0. 0. 0.]
7
(7,)
1


In [149]:
import numpy as np
arr = np.ones(6)
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)


[1. 1. 1. 1. 1. 1.]
(6,)
6
1


In [150]:
import numpy as np

arr = np.full(8,25)

print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[25 25 25 25 25 25 25 25]
(8,)
8
1


In [151]:
import numpy as np
arr = np.empty((2,3))
print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)

[[1. 1. 1.]
 [1. 1. 1.]]
(2, 3)
6
2


In [152]:
import numpy as np

arr = np.arange(0,30,5)

print(arr)
print(arr.shape)
print(arr.size)

[ 0  5 10 15 20 25]
(6,)
6


In [153]:
import numpy as np

arr = np.linspace(0,25,6)

print(arr)
print(arr.shape)
print(arr.size)

[ 0.  5. 10. 15. 20. 25.]
(6,)
6


In [154]:
import numpy as np

arr = np.eye(5,5)

print(arr)
print(arr.shape)
print(arr.size)
print(arr.ndim)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
(5, 5)
25
2


In [155]:
import numpy as np
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [156]:
import numpy as np

arr = np.array([10, 20, 30],dtype = int)
print(arr)
print(arr.dtype)


[10 20 30]
int64


In [157]:
import numpy as np
arr = np.array([10.5, 20.5, 30.5],dtype = float)
print(arr)
print(arr.dtype)

[10.5 20.5 30.5]
float64


In [158]:
import numpy as np
arr = np.array([True, False, True],dtype = bool)
print(arr)
print(arr.dtype)

[ True False  True]
bool


In [159]:
import numpy as np
arr = np.array([10.5, 20.8, 30.2])
new_array = arr.astype(int)
print(new_array)
print(arr)
print(arr.dtype)
print(new_array.dtype)

[10 20 30]
[10.5 20.8 30.2]
float64
int64


In [160]:
import numpy as np

a = np.array([10, 20, 30, 40])
b = np.array([2, 4, 5, 8])

print(a + b)
print(a - b)
print(a * b)
print(a/b)   
print(a * 5)

[12 24 35 48]
[ 8 16 25 32]
[ 20  80 150 320]
[5. 5. 6. 5.]
[ 50 100 150 200]


In [161]:
import numpy as np

a = np.array([10, 20, 30, 40, 50])
b = np.array([15, 20, 25, 40, 45])

print(a>b)
print(a==b)
print(a!= b)
print((a>20) & (a<50))

[False False  True False  True]
[False  True False  True False]
[ True False  True False  True]
[False False  True  True False]


In [162]:
import numpy as np

prices = np.array([100, 200, 300, 400])

print(prices + 50)
print(prices * 1.10)
print(prices / 2)
print(prices ** 2)

[150 250 350 450]
[110. 220. 330. 440.]
[ 50. 100. 150. 200.]
[ 10000  40000  90000 160000]


In [163]:
import numpy as np

numbers = np.array([10, 20, 30, 40, 50])

print(numbers * 3)
print(numbers - 5)
print(numbers / 100)

[ 30  60  90 120 150]
[ 5 15 25 35 45]
[0.1 0.2 0.3 0.4 0.5]


In [164]:
import numpy as np

income = np.array([25000, 40000, 55000, 70000])

new_income = income / 1000

print(new_income)

[25. 40. 55. 70.]


In [165]:
import numpy as np

arr = np.array([-16, -4, 0, 4, 9, 25])

print(np.abs(arr))
print(np.square(arr))


[16  4  0  4  9 25]
[256  16   0  16  81 625]


In [166]:
import numpy as np

numbers = np.array([1, 2, 3])

print(np.exp(numbers))

[ 2.71828183  7.3890561  20.08553692]


In [167]:
import numpy as np

arr = np.array([1, 10, 100, 1000])
print(np.log(arr))

[0.         2.30258509 4.60517019 6.90775528]


In [168]:
import numpy as np

x = np.array([10, 100, 1000])

print(np.log10(x))

[1. 2. 3.]


In [169]:
import numpy as np

x = np.array([5, 15, 25, 35, 45])

print(np.clip(x,10,30))

[10 15 25 30 30]


In [170]:
import numpy as np

x = np.array([0.1, 0.5, 1.0])

print(np.log1p(x))

[0.09531018 0.40546511 0.69314718]


In [171]:
import numpy as np
x = np.array([0, 1, 2, 3])
print(np.exp(x))

[ 1.          2.71828183  7.3890561  20.08553692]


In [172]:
import numpy as np

sales = np.array([1200, 1500, 1800, 1100, 1600])

print(np.sum(sales))

7200


In [173]:
import numpy as np

sales = np.array([1200, 1500, 1800, 1100, 1600])

print(np.mean(sales))

1440.0


In [174]:
import numpy as np
sales = np.array([1200, 1500, 1800, 1100, 1600])
print(np.median(sales))

1500.0


In [175]:
import numpy as np
sales = np.array([1200, 1500, 1800, 1100, 1600])
print(np.min(sales))

1100


In [176]:
import numpy as np
sales = np.array([1200, 1500, 1800, 1100, 1600])
print(np.max(sales))

1800


In [177]:
import numpy as np

scores = np.array([40, 50, 60])


print(np.var(scores))

66.66666666666667


In [178]:
import numpy as np

sales = np.array([1200, 1800, 900, 2500, 1700])

print(np.min(sales))
print(np.argmin(sales))

print(np.max(sales))
print(np.argmax(sales))

900
2
2500
3


In [179]:
import numpy as np

marks = np.array([
    [80, 70, 90],
    [60, 85, 75],
    [95, 88, 92]
])
print(np.sum(marks,axis = 0))
print(np.sum(marks,axis = 1))

[235 243 257]
[240 220 275]


In [180]:
import numpy as np

X = np.array([
    [20, 50000, 5],
    [30, 60000, 7],
    [40, 80000, 10]
])

print(np.mean(X,axis = 0))
print(np.mean(X,axis = 1))

[3.00000000e+01 6.33333333e+04 7.33333333e+00]
[16675.         20012.33333333 26683.33333333]


In [181]:
import numpy as np

x = np.arange(24)

print(x)
print(x.shape)

X = x.reshape(12,2)
c = x.reshape(2,12)
print(X)
print(X.shape)
print(c)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
(24,)
[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]]
(12, 2)
[[ 0  1  2  3  4  5  6  7  8  9 10 11]
 [12 13 14 15 16 17 18 19 20 21 22 23]]


In [182]:
import numpy as np

A = np.zeros((8, 3))


B = np.zeros((5, 8))


print(A.shape)
print(B.shape)


print(B.T.shape)

print(A.T.shape)
print(B.T.shape)

print(A.T @ B.T)
     

(8, 3)
(5, 8)
(8, 5)
(3, 8)
(8, 5)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [183]:
import numpy as np

A = np.zeros((7, 4))
B = np.zeros((4, 6))

A @ B


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [184]:
import numpy as np
B = np.zeros((7, 4))

A = np.zeros((4, 6))

B @ A

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [185]:
import numpy as np

A = np.zeros((6, 4))
B = np.zeros((6, 4))

print(A.T.shape)
print(B.shape)

A.T @ B

(4, 6)
(6, 4)


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [186]:
import numpy as np
a = np.zeros((6,4))
b = np.zeros((6,4))

print(a.T.shape)
print(b.shape)

print(a.T @ b)

(4, 6)
(6, 4)
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
